version: '3'
services:
        prometheus:
                image: "prom/prometheus"
                ports:
                        - "9090:9090"
                volumes: 
                - "/home/hell/prometheus-todoist-exporter/docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml"
        prometheus-todoist-exporter:
                image: "kaisha/todoist-prometheus-exporter"
                volumes: 
                - "/home/hell/prometheus-todoist-exporter/.state:/.state"
                - "/home/hell/prometheus-todoist-exporter/.credentials:/.credentials"
        grafana:
                image: "grafana/grafana"
                ports:
                        - "3000:3000"

        
